### Lista
GET http://localhost:4000/api/users

### Crear usuario
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "name": "Cristina",
    "mail": "cristina@gmail.com",
    "birth": "19/12/2021",
    "notes": []
}

### Ver usuario (MODIFICAR ID)
GET http://localhost:4000/api/users/60c572c613887e4d60491ade

### Borrar usuario (MODIFICAR ID)
DELETE http://localhost:4000/api/users/60bea8c2166e3d357417359b

### Actualizar usuario (MODIFICAR ID)
PUT http://localhost:4000/api/users/60bea984b4cb0206902292c3
Content-Type: application/json

{
    "name": "Pepe"
}

### Lista de Apuntes
GET http://localhost:4000/api/notes

### Crear Apunte
POST http://localhost:4000/api/notes
Content-Type: application/json

{
    "name": "Apunte Fourier",
    "subject": "60c80ade70df0f346472ad38",
    "career": "Ing. Sistemas de información",
    "creator": "60c572c613887e4d60491ade",
    "content": "blah bla bla bla",
    "calification": 0,
    "attached": "pelotas pelotas",
    "category": "Matematíca"
}

### Ver Apunte
GET http://localhost:4000/api/notes/60c805c5364c1418f0a3dcbb

### Borrar Apunte
DELETE http://localhost:4000/api/notes/6192d6b515ac350a4395e940

### Actualizar Apunte
PUT http://localhost:4000/api/notes/60c8063f364c1418f0a3dcbc
Content-Type: application/json

{
    "content": "Fourier Actualizado.pdf"
}

### Lista de Materias
GET http://localhost:4000/api/subjects

### Crear Materia
POST http://localhost:4000/api/subjects
Content-Type: application/json

{
    "name": "Analisis Matematico III",
    "professor": "Mercedes",
    "notes": []
}

### Ver Materia
GET http://localhost:4000/api/subjects/60bea5a65de71f0190afbb42

### Borrar Materia
DELETE http://localhost:4000/api/subjects/60bea8c2166e3d357417359b

### Actualizar Materia
PUT http://localhost:4000/api/subjects/60c80ade70df0f346472ad38
Content-Type: application/json

{
    "professor": "Adrianita"
}


### Crear comentario
POST http://localhost:4000/api/comments
Content-Type: application/json

{
    "creator": "60c572a013887e4d60491adc",
    "content": "holiwis"
}

### Subir archivo
POST http://localhost:4000/api/files
Content-Type: application/json

{
    "url": "C:/Users/emman/Documents/yummi_app/frontendyummi/src/assets/Solucionario-Principio-de-las-Comunicaciones-Jose-Briceno.pdf"
}

### Lista
GET http://localhost:4000/api/files
