### Lista
GET http://localhost:4000/api/users

### Crear usuario
POST http://localhost:4000/api/users
Content-Type: application/json

{
    "name": "Cristina",
    "id": "10953",
    "notes": ["AM2", "MatDisc", "SO"]
}

### Ver usuario (MODIFICAR ID)
GET http://localhost:4000/api/users/60bea5a65de71f0190afbb42

### Borrar usuario (MODIFICAR ID)
DELETE http://localhost:4000/api/users/60bea8c2166e3d357417359b

### Actualizar usuario (MODIFICAR ID)
PUT http://localhost:4000/api/users/60bea984b4cb0206902292c3
Content-Type: application/json

{
    "name": "Pepe"
}

### Lista de Apuntes
GET http://localhost:4000/api/notes

### Crear Apunte
POST http://localhost:4000/api/notes
Content-Type: application/json

{
    "name": "Apunte Fourier",
    "creator": "Pepe",
    "content": "Apunte Serie de Fourier.pdf"
}

### Ver Apunte
GET http://localhost:4000/api/notes/60c805c5364c1418f0a3dcbb

### Borrar Apunte
DELETE http://localhost:4000/api/notes/60c805c5364c1418f0a3dcbb

### Actualizar Apunte
PUT http://localhost:4000/api/notes/60c8063f364c1418f0a3dcbc
Content-Type: application/json

{
    "content": "Fourier Actualizado.pdf"
}

### Lista de Materias
GET http://localhost:4000/api/subjects

### Crear Materia
POST http://localhost:4000/api/subjects
Content-Type: application/json

{
    "name": "Analisis Matematico II",
    "professor": "Mercedes",
    "notes": ["60c8063f364c1418f0a3dcbc", "60c80b2b70df0f346472ad39"]
}

### Ver Materia
GET http://localhost:4000/api/subjects/60bea5a65de71f0190afbb42

### Borrar Materia
DELETE http://localhost:4000/api/subjects/60bea8c2166e3d357417359b

### Actualizar Materia
PUT http://localhost:4000/api/subjects/60c80ade70df0f346472ad38
Content-Type: application/json

{
    "professor": "Adrianita"
}